### ISSUE TITLE
64x48

### ISSUE THREAD

**Issue by cccyd1** [WangChen100/Unbiased-Feature-Position-Alignment-for-Human-Pose-Estimation#1]
请问在w48_384x288_adam_lr1e-3.yaml配置文件中有
DATASET:：
  LOCREF_STDEV: 1.5
和
LOSS:
  OFFSET_WEIGHT: 1.0 
然后在其他分辨率的配置文件就没有     请问是不需要这个设置了吗

**Comment by WangChen100** [comment]
64x48的feature_size = [(17,13),(9,7),(5,4)]



在 2024-09-03 20:12:17，"cccyd1" ***@***.***> 写道：

根据你们提供的程序进行基于hrnet姿态估计模型训练的时候只有384x288分辨率的feature_size = [(97,73),(49,37),(25,19),(13,10)]

128x96的是feature_size = [(33,25),(17,13),(9,7),(5,4)]

那么64x48的是怎么设置的

**Comment by WangChen100** [comment]
> 请问在w48_384x288_adam_lr1e-3.yaml配置文件中有 DATASET:： LOCREF_STDEV: 1.5 和 LOSS: OFFSET_WEIGHT: 1.0 然后在其他分辨率的配置文件就没有 请问是不需要这个设置了吗

你好，感谢你的提问，在默认参数文件中加了，但是建议在配置文件还是加上，我这边也会在配置文件中加上

**Comment by cccyd1** [comment]
还有个问题  64分辨率和128分辨率的是直接无预训练模型的吗，如果有的话麻烦提供一下

**Comment by cccyd1** [comment]
OFFSET_WEIGHT: 1.0
  KPD: 6.0
  这个设置是在所有分辨率下都是这个设置吗
